//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EKDBEntities1 : DbContext
    {
        public EKDBEntities1()
            : base("name=EKDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tOrder> tOrders { get; set; }
        public virtual DbSet<tOrderLine> tOrderLines { get; set; }
        public virtual DbSet<tUser> tUsers { get; set; }
    }
}
